[Appearance]
style=Fusion
custom_palette=true
color_scheme_path=~/.config/qt5ct/colors/Monochrome.conf
icon_theme=Adwaita
standard_dialogs=default

[Fonts]
fixed="JetBrainsMono Nerd Font,10,-1,5,50,0,0,0,0,0"
general="JetBrainsMono Nerd Font,10,-1,5,50,0,0,0,0,0"

[Interface]
stylesheets=/home/bytesimal/.config/qt5ct/qss/monochrome.qss
